global:
  scrape_interval:     3s
  evaluation_interval: 15s
  external_labels:
      monitor: 'example-app'

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: /metrics
    scheme: http
    static_configs:
         - targets: ['api:5050']