version: '2'

services:
  api:
    image: python:3.8.5-alpine3.12
    container_name: api
    working_dir: /var/lib/api
    networks:
      - backend
    ports:
    - "5050:5050"
    volumes:
      - ../api/:/var/lib/api
    command: >
      sh -c "pip install -r api/requirements.txt
      && python3 api/main.py"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus-storage:/var/lib/prometheus
      - ./prometheus-provisioning:/etc/prometheus/
    links:
      - api
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    networks:
      - backend

volumes:
  grafana-storage:
  prometheus-storage:

networks:
  backend:
    driver: "bridge"